# Form implementation generated from reading ui file 'pig.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(94, 121, 255)\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.roll_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.roll_button.setGeometry(QtCore.QRect(150, 410, 120, 80))
        self.roll_button.setMinimumSize(QtCore.QSize(0, 0))
        self.roll_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.roll_button.setFont(font)
        self.roll_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 215, 239);\n"
"    background-color: rgb(231, 0, 151);\n"
"}")
        self.roll_button.setObjectName("roll_button")
        self.hold_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hold_button.setGeometry(QtCore.QRect(330, 410, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.hold_button.setFont(font)
        self.hold_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 215, 239);\n"
"    background-color: rgb(231, 0, 151);\n"
"}")
        self.hold_button.setObjectName("hold_button")
        self.total_points_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.total_points_label.setGeometry(QtCore.QRect(350, 510, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.total_points_label.setFont(font)
        self.total_points_label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 215, 239);\n"
"}")
        self.total_points_label.setObjectName("total_points_label")
        self.turn_points_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.turn_points_label.setGeometry(QtCore.QRect(10, 510, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.turn_points_label.setFont(font)
        self.turn_points_label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 215, 239);\n"
"}")
        self.turn_points_label.setObjectName("turn_points_label")
        self.dice_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.dice_1.setGeometry(QtCore.QRect(200, 180, 200, 200))
        self.dice_1.setAutoFillBackground(False)
        self.dice_1.setStyleSheet("QLabel {\n"
"    background-color: rgb(250, 135, 210)\n"
"}")
        self.dice_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dice_1.setText("")
        self.dice_1.setObjectName("dice_1")
        self.target_score_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.target_score_label.setGeometry(QtCore.QRect(10, 130, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.target_score_label.setFont(font)
        self.target_score_label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 215, 239)\n"
"}")
        self.target_score_label.setObjectName("target_score_label")
        self.turn_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.turn_label.setGeometry(QtCore.QRect(10, 170, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.turn_label.setFont(font)
        self.turn_label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 215, 239);\n"
"}")
        self.turn_label.setObjectName("turn_label")
        self.reset_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(470, 20, 120, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reset_button.setFont(font)
        self.reset_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 215, 239);\n"
"    background-color: rgb(231, 0, 151);\n"
"}")
        self.reset_button.setObjectName("reset_button")
        self.pig_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.pig_label.setGeometry(QtCore.QRect(210, 20, 175, 120))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(65)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.pig_label.setFont(font)
        self.pig_label.setStyleSheet("")
        self.pig_label.setText("")
        self.pig_label.setPixmap(QtGui.QPixmap("game_image.png"))
        self.pig_label.setScaledContents(True)
        self.pig_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pig_label.setObjectName("pig_label")
        self.how_to_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.how_to_button.setGeometry(QtCore.QRect(10, 20, 120, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.how_to_button.setFont(font)
        self.how_to_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 215, 239);\n"
"    background-color: rgb(231, 0, 151);\n"
"}")
        self.how_to_button.setObjectName("how_to_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PIG: The Dice Game"))
        self.roll_button.setText(_translate("MainWindow", "ROLL"))
        self.hold_button.setText(_translate("MainWindow", "HOLD"))
        self.total_points_label.setText(_translate("MainWindow", "TOTAL POINTS: "))
        self.turn_points_label.setText(_translate("MainWindow", "POINTS THIS TURN:"))
        self.target_score_label.setText(_translate("MainWindow", "TARGET SCORE: "))
        self.turn_label.setText(_translate("MainWindow", "TURN #:"))
        self.reset_button.setText(_translate("MainWindow", "RESET GAME"))
        self.how_to_button.setText(_translate("MainWindow", "HOW TO PLAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
